### PR TITLE
NT-867 - fixed number of decimals in approval summaries

### PR DESCRIPTION
**Pull request by NikolaiLarsen**

### CODE REVIEW

**Comment by eiriko2303** [comment]
@reg0 Aha yes Kamil, thats correct, I forgot that 👍 The method is called formatToTwoDecimals. Please change it to this.

**Comment by NikolaiLarsen** [comment]
@reg0 @eiriko2303 Fixed it now :)

**Comment by reg0** [comment]
@NikolaiLarsen does it make sense like that? take number, format it and parseFloat() it back? it will practically remove formatting
either these functions should return strings and then parseFloat() is not needed
or this formatting should be applied on rendering and not where the values are returned

**Comment by NikolaiLarsen** [comment]
@reg0 you are right, i changed it to string :)

**Pull request merged**
